### ISSUE TITLE
Move roles to ansible-galaxy

### ISSUE THREAD

**Issue by karras** [adfinis-sygroup/foreman-ansible#22]
Recently we split our infrastructure roles and pushed them to Galaxy: https://galaxy.ansible.com/adfinis-sygroup/

It would make sense to separate the roles of this repo as well and refactor them at the same time. Basically we could reuse existing roles (e.g. mysql) which improves maintenance and adaptability.

This repo would then serve as a central place to get started with Foreman and provide a set of nice example playbooks for different setups. Installation would be done via ansible-galaxy requirements.yml file.

What's your take @hairmare @keachi @fujexo ?

Migration status:
- [ ] foreman
- [ ] foreman_proxy
- [ ] foreman_yml
- [x] isc_dhcp_server (https://github.com/adfinis-sygroup/ansible-role-isc_dhcp_server)
- [x] mysql (https://github.com/adfinis-sygroup/ansible-role-mariadb)
- [x] nginx (https://github.com/adfinis-sygroup/ansible-role-nginx)
- [ ] passenger_nginx
- [x] sqlite (https://github.com/adfinis-sygroup/ansible-role-sqlite)
- [ ] tftp

**Comment by hairmare** [comment]
Aren't there some "official" roles for the foreman stuff in https://github.com/theforeman/forklift nowadays? Does maintaining our own make sense at this point?

**Comment by karras** [comment]
Migrating the roles is quite easy as they already support multiple distributions. Also the mysql and nginx roles are already there. What needs maintenance is foreman and foreman_proxy due to config changes or similar.

**Comment by keachi** [comment]
forklift is not a role, it's a whole set of roles, playbooks and stuff. I do also not see for which distributions forklift works. If we find good roles for all our supported distributions, we can use those. But instead we can migrate our roles to Ansible Galaxy too.

IMHO we should use our existing roles for nginx and mysql, and extract and update the other roles from this repository.

**Comment by karras** [comment]
Migrated DHCP role: https://github.com/adfinis-sygroup/ansible-role-isc_dhcp_server

**Comment by karras** [comment]
Project archived
